### ISSUE TITLE
Where should I place the directory for the llama-2 model?

### ISSUE THREAD

**Issue by YongTaeIn** [NJU-LHRS/LHRS-Bot#15]
I enjoyed your project. I would like to inquire because there is an error occurring.
 After downloading llama2-7b, I was able to successfully log in to huggingface through the terminal.

However, the following error occurs during the inference process.

OSError: llama/Llama-2-7b-chat is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

How can I solve this?

**Comment by pUmpKin-Co** [comment]
HI~Thanks for you interest.

You should change the path in config for directing to your downloaded folder. The instruction can be founded at [here](https://github.com/NJU-LHRS/LHRS-Bot#:~:text=Done!-,Mannually%20download%3A,-Download%20all%20the).

**Comment by pUmpKin-Co** [comment]
Hi~
We deploy our model based on the huggingface version. 
Therefore, it's better for you to get lience from [here](https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main) and device whether you need to download all the files or just paste `meta-llama/Llama-2-7b-hf` into the config path.

**Comment by YongTaeIn** [comment]
Thanks for helping :)
