### ISSUE TITLE
A question about the Stage2 RSVG training data

### ISSUE THREAD

**Issue by xuliu-cyber** [NJU-LHRS/LHRS-Bot#29]
Hello, I found the RSVG datas used in stage2 are made up of RSVG-val and RSVG-test. And the VG evaluation dataset is RSVG-test.
Is it a mistake?

**Comment by pUmpKin-Co** [comment]
Oops!

Sorry for the late reply. What happend is that I upload a wrong file through my cloud.

Have fixed and uploaded correct one.

Thank you for your pointing out!

**Comment by xuliu-cyber** [comment]
OK.

**Comment by xuliu-cyber** [comment]
OK, Thank you for the reply
