### ISSUE TITLE
Is the LHRS-Align and LHRS-Instruct publicly available?

### ISSUE THREAD

**Issue by YonghuiTAN22** [NJU-LHRS/LHRS-Bot#6]

**Comment by pUmpKin-Co** [comment]
Hi, Thanks for your interest.

Our dataset is currently unavailable, but it will be released after our paper is accepted. 

Please stay tuned for updates.

**Comment by pUmpKin-Co** [comment]
Hi!

We have release our data! Please see the instruction from the main page.
