### ISSUE TITLE
How much GPU memory is needed to run the demo

### ISSUE THREAD

**Issue by Nevaeh7** [NJU-LHRS/LHRS-Bot#7]

**Comment by pUmpKin-Co** [comment]
18GB of RAM suffices for loading processes, while 20GB of RAM is considered safe for serving and engaging in conversations (loading with bf16 or fp16).

**Comment by Nevaeh7** [comment]
> 18GB RAM 足以用于加载进程，而 20GB RAM 对于服务和参与对话被认为是安全的（使用 bf16 或 fp16 加载）。

Thanks your reply
